- name: install GKS welcome.html
  template: src=gks_welcome.html.j2 dest="{{ galaxy_server_dir }}/static/welcome.html"
- name: install dependency_resolvers_conf.xml.sample
  template: src=dependency_resolvers_conf.xml.sample.j2 dest="{{ galaxy_server_dir }}/config/dependency_resolvers_conf.xml"

- name:  Copy additional files
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ galaxy_user_name }}
  with_items:
    - "{{ additional_files_list }}"
  tags:
   - persists_galaxy
